default: &default
  adapter: postgresql
  encoding: unicode
  username: rishitha
  password: password
  host: localhost
  port: 5433
  pool: 5

development:
  <<: *default
  database: ecommerce_app_development

test:
  <<: *default
  database: ecommerce_app_test
